import React, { useState } from "react";
import Navbar from "../components/Navbar";
import Slideshow from "../components/slideshow";
import Footer from "../components/footer";
import Typewriter from 'typewriter-effect';

import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";


import Cards from "../components/Card";
import Graph from "../components/Graph";
import AccScoreImg from '../images/Acc_Score.png';
import RocCurveImg from '../images/ROC_Curve.png';
// import EmailPopup from "../components/EmailPopup";


function Home() {
  // const [isPopupOpen, setIsPopupOpen] = useState(false);

  useEffect(() => {
    AOS.init();
  }, []);

  // const handleOpenPopup = () => {
  //   setIsPopupOpen(true);
  // };

  // const handleClosePopup = () => {
  //   setIsPopupOpen(false);
  // };

  return (
    <> 
    
      <Navbar />
    
    <div className="bg-blue-70 overflow-hidden" style={{ backgroundImage: `url(https://api.ctia.org/wp-content/uploads/2018/03/emergency_preparedness_2.jpg)`, backgroundSize: 'cover', backgroundPosition: 'center'}}>

    
      {/* Button to Open Popup */}
      {/* <div className="flex justify-center mt-10">
          <button
            onClick={handleOpenPopup}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg shadow-md hover:bg-blue-700"
          >
            Stay Updated on Flood Alerts
          </button>
        </div> */}

      {/* Email Popup */}
      {/* <EmailPopup isOpen={isPopupOpen} onClose={handleClosePopup} /> */}

      <div 
       style={{
      color:"skyblue",
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      fontSize:'38px',
      fontFamily:'monospace',
      fontWeight:'bolder',
      marginTop:'100px'
    }}>

      <Typewriter
  options={{
    strings: ['A-WARN','A Forewarning System'],
    autoStart:true,
    cursor:null,
    loop:true,
    delay: 100,
    
  }}></Typewriter>
</div>
      <div data-aos="zoom-out-up" data-aos-duration="3000" className="mt-10 ">
        <Slideshow />
      </div>

      <div className="mt-20 mb-20 flex justify-evenly ">
        <div data-aos="fade-right"
     
     data-aos-duration="2000">
        <Cards
          calamity="Avalanche"
          content="Avalanches, the rapid downhill movement of snow, can be devastating natural phenomena, posing significant risks to individuals and communities in mountainous regions. Understanding the factors contributing to avalanches and adopting appropriate safety measures are essential for mitigating these dangers."
          img="https://media.istockphoto.com/id/530528657/photo/dry-snow-avalanche-with-a-powder-cloud-caucasus.jpg?s=2048x2048&w=is&k=20&c=_Uq5Umt9c6eBOq1keBZGNslMAE7sV9XO6YT6gxZSEzc="
          link="https://en.wikipedia.org/wiki/Avalanche"
        />
        </div>
        <div data-aos="fade-up"
     
     data-aos-duration="1500">
        <Cards calamity="Tsunami" content="Tsunamis, often referred to as seismic sea waves,are a series of long ocean waves generated by disturbances such as underwater earthquakes, volcanic eruptions, or landslides. These immense waves can travel across entire ocean basins and are characterized by their long wavelengths and high velocities." 
        img="https://i.ytimg.com/vi/KN65bEIZr4o/maxresdefault.jpg"
        link="https://en.wikipedia.org/wiki/Tsunami"
        />
        </div>
        <div data-aos="fade-left"
     
     data-aos-duration="1500">
        <Cards calamity="Flood" content="Floods are one of the most common and destructive natural disasters worldwide. They occur when an overflow of water submerges land that is usually dry, affecting communities, infrastructure, and the environment. Understanding the causes, impacts, and preparedness measures for floods is crucial for mitigating risks and ensuring safety."
        img="https://as2.ftcdn.net/v2/jpg/01/14/56/71/1000_F_114567125_EgGAPtSzutZKaVwKAMPcKAe3MaHPMz8Q.jpg" 
        link="https://en.wikipedia.org/wiki/Flood"
        />
         </div>
      </div>

      {/* Graph */}
      <div className="mt-20 mb-20 flex justify-evenly ">
        <div data-aos="fade-right"
     
     data-aos-duration="2000">
        <Graph
          calamity="Yearly Accuracy Graph"
          content="Accuracy scores of prediction for past year, 2023-24"
          img={AccScoreImg}
          
        />
        </div>

        <div data-aos="fade-left"
     
     data-aos-duration="1500">
        <Graph calamity="ROC Curve" content=" 
        
        "
         img={RocCurveImg} />
         </div>
      </div>

      <div className="bg-black-500" data-aos="fade-down" data-aos-duration="3000">
        <Footer />
      </div>
      </div>
    </>
  );
}

export default Home;
